# Generated by Django 3.1.4 on 2020-12-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
